sudo: required

services:
  - docker

before_install:
  - docker pull busybox:glibc
  - docker pull busybox:musl

script:
  - ./docker-diff busybox:glibc busybox:musl;  if [ $? = 0 ]; then exit 1; fi
  - ./docker-diff busybox:glibc busybox:glibc; if [ $? = 1 ]; then exit 1; fi
